/**
 * Represents a model for an employee in the system.
 *
 * This class is annotated with JPA annotations to define its mapping to a database table.
 */
package com.omatheusmesmo.employeeapp.model;

import lombok.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "employees")
public class Employee {

    /**
     * Unique identifier for the employee, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the employee.
     *
     * This field is set as non-null to ensure data validation on insertion.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The email address of the employee, unique across records.
     *
     * This field is set as non-null to enforce data validation and avoid duplicate entries.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The position or role of the employee in the organization.
     *
     * This field is set as non-null to ensure data integrity on insertion.
     */
    @Column(nullable = false)
    private String position;

    /**
     * The salary of the employee, not null for meaningful records.
     */
    @Column(nullable = false)
    private Double salary;
}