package com.omatheusmesmo.EmployeeAPI.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * Represents an Employee entity in the database.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "employees")
public class Employee {

    /**
     * Unique identifier for the employee, automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the employee.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The email address of the employee, unique across all employees.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The position held by the employee.
     */
    @Column(nullable = false)
    private String position;

    /**
     * The salary amount for the employee's position.
     */
    @Column(nullable = false)
    private Double salary;
}