/**
 * Represents a repository for managing employees in the database.
 *
 * This interface is generated by Spring Data JPA and provides basic CRUD operations for the Employee entity.
 */
package com.omatheusmesmo.EmployeeAPI.repository;

import com.omatheusmesmo.EmployeeAPI.model.Employee;
import org.springframework.data.jpa.repository.JpaRepository;

public interface EmployeeRepository extends JpaRepository<Employee, Long> {
    // No additional methods needed as they are provided by Spring Data JPA
}